column_width = 160
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "None"
# Preserve intermediate whitespace for things like comment alignment in init.lua
collapse_simple_statement = false
